### ISSUE TITLE
Typo on Quiz Unlock Screen

### ISSUE THREAD

**Issue by samuelgrant** [deepcove-trust/discover_deep_cove#158]
The quiz unlocks screen informs users that non-students can unlock all quizzes using a special code in the main hostel. 

It makes no sense for this code to be in the main hostel, as students could easily find it. This UI should be updated to suggest the code can be found in the office. 

<img src="https://user-images.githubusercontent.com/15701407/109410769-31dca880-7a02-11eb-9ed3-10f0ffeb3840.png" height="500">

**Comment by MitchellQ** [comment]
I'll take care of this

**Comment by MitchellQ** [comment]
Awaiting merge and deploy
